### ISSUE TITLE
Rendering axioms

### ISSUE THREAD

**Issue by Demirrr** [dice-group/owlapy#104]
```
from owlapy.owl_ontology_manager import SyncOntologyManager
from owlapy.render import owl_expression_to_dl
ontology_path = "KGs/Family/father.owl"
onto = SyncOntologyManager().load_ontology(ontology_path)
for owl_subclass_of_axiom in onto.get_tbox_axioms():
    print(owl_subclass_of_axiom)
    print(owl_expression_to_dl(owl_subclass_of_axiom))
```

**Comment by Demirrr** [comment]
```python
from owlapy.class_expression import OWLClass, OWLObjectIntersectionOf, OWLObjectSomeValuesFrom
from owlapy.owl_property import OWLObjectProperty
from owlapy import owl_expression_to_sparql, owl_expression_to_dl
from owlapy.owl_ontology_manager import OntologyManager
from owlapy.owl_axiom import OWLDeclarationAxiom, OWLClassAssertionAxiom
from owlapy.owl_individual import OWLNamedIndividual, IRI
from owlapy.static_funcs import create_ontology
# Using owl classes to create a complex class expression
male = OWLClass("http://example.com/society#male")
hasChild = OWLObjectProperty("http://example.com/society#hasChild")
hasChild_male = OWLObjectSomeValuesFrom(hasChild, male)
teacher = OWLClass("http://example.com/society#teacher")
teacher_that_hasChild_male = OWLObjectIntersectionOf([hasChild_male, teacher])

# Create an ontology via ontology manager directly
ontology = create_ontology("file:/example_ontology.owl",with_owlapi=True)
john = OWLNamedIndividual("http://example.com/society#john")
male_declaration_axiom = OWLDeclarationAxiom(male)
hasChild_declaration_axiom = OWLDeclarationAxiom(hasChild)
john_declaration_axiom = OWLDeclarationAxiom(john)
john_a_male_assertion_axiom = OWLClassAssertionAxiom(john, male)
axioms=[male_declaration_axiom, hasChild_declaration_axiom, john_declaration_axiom, john_a_male_assertion_axiom]
ontology.add_axiom(axioms)
```

leads to the following error:
```
Traceback (most recent call last):
  File "/home/cdemir/Desktop/Softwares/owlapy/asd.py", line 23, in <module>
    ontology.add_axiom(axioms)
  File "/home/cdemir/Desktop/Softwares/owlapy/owlapy/owl_ontology.py", line 1103, in add_axiom
    self.owlapi_ontology.addAxioms(self.mapper.map_(axiom))
  File "/home/cdemir/anaconda3/envs/temp_owlapy/lib/python3.10/functools.py", line 926, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/home/cdemir/Desktop/Softwares/owlapy/owlapy/owlapi_mapper.py", line 509, in _
    java_list.add(self.map_(item))
  File "/home/cdemir/anaconda3/envs/temp_owlapy/lib/python3.10/functools.py", line 926, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/home/cdemir/Desktop/Softwares/owlapy/owlapy/owlapi_mapper.py", line 291, in _
    return OWLDeclarationAxiomImpl(self.map_(e.get_entity()), self.map_(e.annotations()))
  File "/home/cdemir/anaconda3/envs/temp_owlapy/lib/python3.10/functools.py", line 926, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/home/cdemir/Desktop/Softwares/owlapy/owlapy/owlapi_mapper.py", line 156, in _
    return self.parser.parse(owl_expression_to_manchester(e))
org.semanticweb.owlapi.manchestersyntax.renderer.org.semanticweb.owlapi.manchestersyntax.renderer.ParserException: org.semanticweb.owlapi.manchestersyntax.renderer.ParserException: Encountered male at line 1 column 1. Expected one of:
	Class name
	Object property name
	Data property name
	inverse
	not
	(
	{
```
The error cause by `owl_expression_to_manchester(e)` 

```python
for i in axioms:
    print(owl_expression_to_manchester(i))
```

```
Traceback (most recent call last):
  File "/home/cdemir/Desktop/Softwares/owlapy/asd.py", line 26, in <module>
    print(owl_expression_to_manchester(i))
  File "/home/cdemir/Desktop/Softwares/owlapy/owlapy/render.py", line 538, in owl_expression_to_manchester
    return ManchesterRenderer.render(o)
  File "/home/cdemir/anaconda3/envs/temp_owlapy/lib/python3.10/functools.py", line 926, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/home/cdemir/Desktop/Softwares/owlapy/owlapy/render.py", line 379, in render
    raise NotImplementedError
NotImplementedError
```

Suggestions: We need to add tests in our code.

**Comment by Demirrr** [comment]
Summary:
```python
from owlapy.owl_ontology_manager import SyncOntologyManager
ontology=SyncOntologyManager().create_ontology("file:/example_ontology.owl")
for owl_subclass_of_axiom in SyncOntologyManager().load_ontology("KGs/Family/father.owl").get_tbox_axioms():
    ontology.add_axiom(owl_subclass_of_axiom)
```

Do you think that you can fix it @alkidbaci ?

**Comment by alkidbaci** [comment]
So it seems like `ManchesterOWLSyntaxClassExpressionParser` of _owlapi_ cannot parse classes that don't exist in the ontology. So when you want to add a new class through `OWLDeclarationAxiom` it tries to parse it to _owlapi_ format before adding it. Its like a chicken-egg problem. A solution for this would be that the mapper per should map atomic classes without using the parser.

**Comment by alkidbaci** [comment]
The problem that still prevails is when adding an axiom which contain some kind of complex class expression, normally the ontology `add_axiom` method will automatically add the missing classes but in our case that is restricted by the fact that the Manchester parser needs the class to exist in the ontology before parsing. 

Now the solutions for this would be:
1. To implement mapping function for each distinct type of class expression (and stop using the Manchester parser for it)
2. Implement a dynamic entity checker (an owlapi class which is used as an argument to a Manchester parser) that does not check for existing entities. I'm working on this second point and so far i have implemented the class, seems to work with complex class expressions but there are some unexpected hidden "issues" (a class is added twice in the ontology) which I noticed and I'm trying to fix.

**Comment by Demirrr** [comment]
Thank you for the analysis of the issue❤️
