### ISSUE TITLE
Error at converting Cardinality Restrictions over nominals into SPARQL queries

### ISSUE THREAD

**Issue by Demirrr** [dice-group/owlapy#3]
```python
from owlapy.render import DLSyntaxObjectRenderer
from owlapy.model import *
from owlapy.owl2sparql.converter import Owl2SparqlConverter
ce=OWLObjectMinCardinality(cardinality=1,property=OWLObjectProperty(IRI.create('http://example.com/society#hasChild')),filler=OWLObjectOneOf(OWLNamedIndividual(IRI('http://www.benchmark.org/family#','F3F42'))))
print(DLSyntaxObjectRenderer().render(ce))
print(Owl2SparqlConverter().as_query("?x", ce))

```
leads to

```
≥ 1 hasChild.{F3F42}
Traceback (most recent call last):
  File "/home/demir/Desktop/Softwares/Ontolearn/sparql_converter.py", line 8, in <module>
    print(Owl2SparqlConverter().as_query("?x", ce))
  File "/home/demir/anaconda3/envs/venv/lib/python3.10/site-packages/owlapy/owl2sparql/converter.py", line 627, in as_query
    parseQuery(query)
  File "/home/demir/anaconda3/envs/venv/lib/python3.10/site-packages/rdflib/plugins/sparql/parser.py", line 1542, in parseQuery
    return Query.parseString(q, parseAll=True)
  File "/home/demir/anaconda3/envs/venv/lib/python3.10/site-packages/pyparsing/util.py", line 256, in _inner
    return fn(self, *args, **kwargs)
  File "/home/demir/anaconda3/envs/venv/lib/python3.10/site-packages/pyparsing/core.py", line 1200, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected SelectQuery, found '{'  (at char 29), (line:3, col:1)

```
Similarly, (perhaps again expectedly) mapping doesn't work over multiple nominals
```python
from owlapy.render import DLSyntaxObjectRenderer
from owlapy.model import *
from owlapy.owl2sparql.converter import Owl2SparqlConverter
ce=OWLObjectMinCardinality(cardinality=1,
                           property=OWLObjectProperty(IRI.create('http://example.com/society#hasChild')),
                           filler=OWLObjectOneOf(
                               (OWLNamedIndividual(IRI('http://www.benchmark.org/family#','F3F42')),
                                OWLNamedIndividual(IRI('http://www.benchmark.org/family#','F3F44')))))
print(DLSyntaxObjectRenderer().render(ce))
print(Owl2SparqlConverter().as_query("?x", ce))

```

```
≥ 1 hasChild.{F3F42 ⊔ F3F44}
Traceback (most recent call last):
  File "/home/demir/Desktop/Softwares/Ontolearn/sparql_converter.py", line 10, in <module>
    print(Owl2SparqlConverter().as_query("?x", ce))
  File "/home/demir/anaconda3/envs/venv/lib/python3.10/site-packages/owlapy/owl2sparql/converter.py", line 627, in as_query
    parseQuery(query)
  File "/home/demir/anaconda3/envs/venv/lib/python3.10/site-packages/rdflib/plugins/sparql/parser.py", line 1542, in parseQuery
    return Query.parseString(q, parseAll=True)
  File "/home/demir/anaconda3/envs/venv/lib/python3.10/site-packages/pyparsing/util.py", line 256, in _inner
    return fn(self, *args, **kwargs)
  File "/home/demir/anaconda3/envs/venv/lib/python3.10/site-packages/pyparsing/core.py", line 1200, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected SelectQuery, found '{'  (at char 29), (line:3, col:1)

```

The same exception also occurs for `OWLObjectMaxCardinality` and `OWLObjectExactCardinality`
We need to create a SPARQL query from `≥ 1 hasChild.{F3F42}` . It would be great if one of you could take care of it
@nkaralis @bigerl @alkidbaci 

For the context, the SPARQL mapping works perfectly well if filler is not `OWLObjectOneOf`.

**Comment by Demirrr** [comment]
I guess the error stems from  converting an expression involving `OWLObjectOneOf `

```python
ce=OWLObjectSomeValuesFrom(property=OWLObjectProperty(IRI('http://www.benchmark.org/family#','hasSibling')),filler=OWLObjectOneOf((OWLNamedIndividual(IRI('http://www.benchmark.org/family#','F6F84')),)))
print(DLSyntaxObjectRenderer().render(ce))
print(Owl2SparqlConverter().as_query("?x", ce))

```

```
∃ hasSibling.{F6F84}
Traceback (most recent call last):
  File "/home/demir/Desktop/Softwares/Ontolearn/sparql_converter.py", line 8, in <module>
    print(Owl2SparqlConverter().as_query("?x", ce))
  File "/home/demir/anaconda3/envs/venv/lib/python3.10/site-packages/owlapy/owl2sparql/converter.py", line 627, in as_query
    parseQuery(query)
  File "/home/demir/anaconda3/envs/venv/lib/python3.10/site-packages/rdflib/plugins/sparql/parser.py", line 1542, in parseQuery
    return Query.parseString(q, parseAll=True)
  File "/home/demir/anaconda3/envs/venv/lib/python3.10/site-packages/pyparsing/util.py", line 256, in _inner
    return fn(self, *args, **kwargs)
  File "/home/demir/anaconda3/envs/venv/lib/python3.10/site-packages/pyparsing/core.py", line 1200, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected SelectQuery, found 'FILTER'  (at char 86), (line:4, col:2)
```

**Comment by alkidbaci** [comment]
Why use `Owl2SparqlConverter().as_query` and not `Owl2SparqlConverter().convert` ?

**Comment by Demirrr** [comment]
Because `Owl2SparqlConverter().convert` does not share a valid SPARQL query in string but a list of strings. 
We should have a function (instead of a class)
`from owlapy.owl2sparql.converter import owl_expression_to_sparql`
to convert an OWL class expression into a SPARQL query. Would you like to take care of it ?
